from __future__ import annotations

from autoscholar.citation.common import (
    clean_bib_field_text,
    first_author_surname,
    infer_entry_type,
    normalize_text,
    paper_key,
    slugify,
    title_key_words,
)
from autoscholar.io import read_jsonl, write_text
from autoscholar.models import SelectedCitationRecord
from autoscholar.workspace import Workspace


def _escape_bibtex(value: str) -> str:
    text = clean_bib_field_text(value)
    replacements = {
        "\\": "\\textbackslash{}",
        "{": "\\{",
        "}": "\\}",
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def _build_citekeys(records: list[SelectedCitationRecord]) -> dict[str, str]:
    used: dict[str, str] = {}
    citekeys: dict[str, str] = {}
    papers = []
    for record in records:
        for selected in record.selected_papers:
            papers.append(selected.paper)

    for paper in sorted(papers, key=lambda item: (first_author_surname(item), item.year or 0, normalize_text(item.title).lower())):
        identifier = paper_key(paper)
        base = f"{first_author_surname(paper)}{paper.year or 'nodate'}{title_key_words(paper.title)}"
        candidate = slugify(base) or "refnodateuntitled"
        suffix = ord("a")
        while candidate in used and used[candidate] != identifier:
            candidate = f"{slugify(base)}{chr(suffix)}"
            suffix += 1
        used[candidate] = identifier
        citekeys[identifier] = candidate
    return citekeys


def write_bibtex(workspace: Workspace) -> tuple[int, dict[str, str]]:
    records = read_jsonl(workspace.require_path("artifacts", "selected_citations"), SelectedCitationRecord)
    papers: dict[str, object] = {}
    for record in records:
        for selected in record.selected_papers:
            papers.setdefault(paper_key(selected.paper), selected.paper)

    citekeys = _build_citekeys(records)
    entries: list[str] = []
    for identifier, paper in sorted(papers.items(), key=lambda item: item[0]):
        entry_type, venue_field = infer_entry_type(paper)
        fields: list[tuple[str, str]] = [
            ("author", " and ".join(clean_bib_field_text(author) for author in paper.authors)),
            ("title", _escape_bibtex(paper.title)),
        ]
        if paper.year:
            fields.append(("year", str(paper.year)))
        venue = clean_bib_field_text(paper.venue)
        if venue and venue_field:
            fields.append((venue_field, _escape_bibtex(venue)))
        doi = normalize_text(paper.doi)
        if doi:
            fields.append(("doi", doi.lower()))

        lines = [f"@{entry_type}{{{citekeys[identifier]},"]
        for name, value in fields:
            if not value:
                continue
            if name == "title":
                lines.append(f"  {name} = {{{{{value}}}}},")
            else:
                lines.append(f"  {name} = {{{value}}},")
        lines.append("}")
        entries.append("\n".join(lines))

    content = "\n".join(
        [
            "% Auto-generated by AutoScholar v2.",
            f"% Entry count: {len(entries)}",
            "",
            "\n\n".join(entries),
            "",
        ]
    )
    write_text(workspace.require_path("artifacts", "references_bib"), content)
    return len(entries), citekeys
